import type { CSSProperties } from 'react';
import type { LucideProps } from 'lucide-react';
import {
  Activity,
  BookOpenText,
  Bot,
  Boxes,
  BrainCircuit,
  ClipboardList,
  Cpu,
  Database,
  FileClock,
  FileText,
  FileSearch,
  Gauge,
  GitBranch,
  GitFork,
  Home,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  LineChart,
  Menu,
  MessageSquare,
  MessageSquareText,
  Network,
  PenLine,
  Plug,
  ScanLine,
  Settings2,
  Sparkles,
  Stethoscope,
  Tags,
  Waypoints,
  Workflow,
} from 'lucide-react';
import {
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  AudioOutlined,
  AuditOutlined,
  BankOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  BellOutlined,
  BookOutlined,
  BranchesOutlined,
  BulbOutlined,
  CalendarOutlined,
  CameraOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  CloseCircleOutlined,
  CloudOutlined,
  CloudServerOutlined,
  ClusterOutlined,
  CommentOutlined,
  CompassOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DiffOutlined,
  DotChartOutlined,
  DownloadOutlined,
  EditOutlined,
  EnvironmentOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileProtectOutlined,
  FileTextOutlined,
  FileSearchOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOpenOutlined,
  FontColorsOutlined,
  FormOutlined,
  FunctionOutlined,
  FundOutlined,
  GatewayOutlined,
  GlobalOutlined,
  GoldOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HighlightOutlined,
  HistoryOutlined,
  HomeOutlined,
  HourglassOutlined,
  ImportOutlined,
  InboxOutlined,
  InfoCircleOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MedicineBoxOutlined,
  MenuOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  MobileOutlined,
  MonitorOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  OpenAIOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PauseCircleOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusSquareOutlined,
  PrinterOutlined,
  ProfileOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  ReadOutlined,
  RedoOutlined,
  ReloadOutlined,
  RetweetOutlined,
  RobotOutlined,
  RocketOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SendOutlined,
  SettingOutlined,
  ShareAltOutlined,
  ShopOutlined,
  SkinOutlined,
  SlidersOutlined,
  SnippetsOutlined,
  SoundOutlined,
  StarOutlined,
  StockOutlined,
  StopOutlined,
  SubnodeOutlined,
  SwapOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WarningOutlined,
  WifiOutlined,
} from '@ant-design/icons';
import type { AntdIconProps } from '@ant-design/icons/lib/components/AntdIcon';

/**
 * 图标渲染：兼容两套图标库。
 * - 新可选图标来自阿里官方图标库 @ant-design/icons（Outlined 系列），
 *   选项带中文名、按场景分组，见 ICON_OPTION_GROUPS。
 * - 存量数据里已存的 lucide 图标名继续由 lucide 渲染。
 * 未知名称回退 LayoutDashboard。
 */

const ANTD_ICONS = {
  // 导航与布局
  HomeOutlined, AppstoreOutlined, MenuOutlined, LayoutOutlined, DashboardOutlined,
  CompassOutlined, GlobalOutlined, DeploymentUnitOutlined, EnvironmentOutlined,
  // 智能与算法
  RobotOutlined, OpenAIOutlined, BulbOutlined, ThunderboltOutlined, ExperimentOutlined,
  FunctionOutlined, ControlOutlined, AimOutlined,
  // 数据与分析
  DatabaseOutlined, TableOutlined, FileSearchOutlined, FolderOpenOutlined, CloudServerOutlined,
  HddOutlined, BarChartOutlined, LineChartOutlined, PieChartOutlined, DotChartOutlined,
  FundOutlined, StockOutlined, SlidersOutlined, GroupOutlined, PartitionOutlined,
  // 知识与文档
  BookOutlined, ReadOutlined, FileTextOutlined, FileDoneOutlined, ProfileOutlined,
  SnippetsOutlined, ContainerOutlined, AuditOutlined, FileAddOutlined, FolderAddOutlined,
  // 标注与编辑
  TagsOutlined, EditOutlined, FormOutlined, HighlightOutlined, FontColorsOutlined,
  CheckSquareOutlined, CopyOutlined, DiffOutlined,
  // 医疗与人员
  MedicineBoxOutlined, HeartOutlined, FileProtectOutlined, ScheduleOutlined, MonitorOutlined,
  UserOutlined, TeamOutlined, SafetyOutlined, PlusSquareOutlined,
  // 接口与集成
  ApiOutlined, LinkOutlined, NodeIndexOutlined, BranchesOutlined, MergeCellsOutlined,
  ShareAltOutlined, ClusterOutlined, ApartmentOutlined, SubnodeOutlined, GatewayOutlined,
  RetweetOutlined, SwapOutlined,
  // 系统与运维
  SettingOutlined, ToolOutlined, CloudOutlined, KeyOutlined, LockOutlined,
  SafetyCertificateOutlined, AlertOutlined, BellOutlined, EyeOutlined, SyncOutlined,
  HistoryOutlined, RocketOutlined, SendOutlined, SearchOutlined, FilterOutlined,
  ScanOutlined, QrcodeOutlined, BarcodeOutlined, PrinterOutlined, SaveOutlined,
  UploadOutlined, DownloadOutlined, ImportOutlined, ExportOutlined, ReloadOutlined, RedoOutlined,
  // 资产与机构
  GoldOutlined, InboxOutlined, BankOutlined, ShopOutlined, CreditCardOutlined, WalletOutlined,
  // 时间与消息
  ClockCircleOutlined, CalendarOutlined, FieldTimeOutlined, HourglassOutlined, MessageOutlined,
  CommentOutlined, NotificationOutlined, MailOutlined, PhoneOutlined, CustomerServiceOutlined,
  // 媒体与设备
  VideoCameraOutlined, AudioOutlined, PictureOutlined, CameraOutlined, MobileOutlined,
  TabletOutlined, LaptopOutlined, DesktopOutlined, WifiOutlined, SoundOutlined,
  PaperClipOutlined, PushpinOutlined, SkinOutlined,
  // 状态与标记
  StarOutlined, FlagOutlined, TrophyOutlined, FireOutlined, CrownOutlined,
  CheckCircleOutlined, CloseCircleOutlined, InfoCircleOutlined, QuestionCircleOutlined,
  WarningOutlined, StopOutlined, PlayCircleOutlined, PauseCircleOutlined,
  PlusCircleOutlined, MinusCircleOutlined,
} as const;

// 存量 lucide 图标（历史数据里的 icon 值继续可用）
const ICONS = {
  BookOpenText,
  Home,
  Boxes,
  BrainCircuit,
  Cpu,
  FileText,
  FileSearch,
  Gauge,
  GitFork,
  Settings2,
  Menu,
  Library,
  PenLine,
  LineChart,
  Sparkles,
  Database,
  Waypoints,
  KeyRound,
  Layers,
  LayoutDashboard,
  MessageSquare,
  MessageSquareText,
  Network,
  Stethoscope,
  Tags,
  Workflow,
  ClipboardList,
  ScanLine,
  Activity,
  Bot,
  FileClock,
  GitBranch,
  Plug,
} as const;

export type IconName = keyof typeof ICONS | keyof typeof ANTD_ICONS;

type AntdIconComponent = React.ComponentType<AntdIconProps>;

export function LucideIcon({ name, size = 16, ...props }: { name?: string; size?: number } & LucideProps) {
  const AntdIcon = name && name in ANTD_ICONS ? (ANTD_ICONS[name as keyof typeof ANTD_ICONS] as AntdIconComponent) : null;
  if (AntdIcon) {
    const { strokeWidth, absoluteStrokeWidth, color, style, rotate, ...rest } = props;
    const nextStyle: CSSProperties = { fontSize: size, ...(color ? { color } : {}), ...style };
    return <AntdIcon {...(rest as AntdIconProps)} style={nextStyle} rotate={typeof rotate === 'number' ? rotate : undefined} />;
  }
  const Icon = (name && name in ICONS ? ICONS[name as keyof typeof ICONS] : LayoutDashboard);
  return <Icon size={size} {...props} />;
}

export type IconOption = { value: string; label: string };
export type IconOptionGroup = { label: string; options: IconOption[] };

/** 图标选择器的分组选项（中文名）；value 为图标导出名/存量名。 */
export const ICON_OPTION_GROUPS: IconOptionGroup[] = [
  {
    label: '导航与布局',
    options: [
      { value: 'HomeOutlined', label: '首页' },
      { value: 'AppstoreOutlined', label: '应用网格' },
      { value: 'MenuOutlined', label: '菜单' },
      { value: 'LayoutOutlined', label: '布局' },
      { value: 'DashboardOutlined', label: '仪表盘' },
      { value: 'CompassOutlined', label: '指南针' },
      { value: 'GlobalOutlined', label: '门户' },
      { value: 'DeploymentUnitOutlined', label: '架构' },
      { value: 'EnvironmentOutlined', label: '位置' },
    ],
  },
  {
    label: '智能与算法',
    options: [
      { value: 'RobotOutlined', label: '智能体' },
      { value: 'OpenAIOutlined', label: '大模型' },
      { value: 'BulbOutlined', label: '灵感' },
      { value: 'ThunderboltOutlined', label: '高效' },
      { value: 'ExperimentOutlined', label: '实验' },
      { value: 'FunctionOutlined', label: '函数' },
      { value: 'ControlOutlined', label: '控制台' },
      { value: 'AimOutlined', label: '目标' },
    ],
  },
  {
    label: '数据与分析',
    options: [
      { value: 'DatabaseOutlined', label: '数据库' },
      { value: 'TableOutlined', label: '数据表' },
      { value: 'FileSearchOutlined', label: '数据检索' },
      { value: 'FolderOpenOutlined', label: '目录' },
      { value: 'CloudServerOutlined', label: '云服务器' },
      { value: 'HddOutlined', label: '存储' },
      { value: 'BarChartOutlined', label: '柱状图' },
      { value: 'LineChartOutlined', label: '折线图' },
      { value: 'PieChartOutlined', label: '饼图' },
      { value: 'DotChartOutlined', label: '散点图' },
      { value: 'FundOutlined', label: '趋势分析' },
      { value: 'StockOutlined', label: '行情' },
      { value: 'SlidersOutlined', label: '指标' },
      { value: 'GroupOutlined', label: '分组统计' },
      { value: 'PartitionOutlined', label: '分区' },
    ],
  },
  {
    label: '知识与文档',
    options: [
      { value: 'BookOutlined', label: '知识库' },
      { value: 'ReadOutlined', label: '阅读' },
      { value: 'FileTextOutlined', label: '文档' },
      { value: 'FileDoneOutlined', label: '办结文档' },
      { value: 'ProfileOutlined', label: '档案' },
      { value: 'SnippetsOutlined', label: '摘录' },
      { value: 'ContainerOutlined', label: '容器' },
      { value: 'AuditOutlined', label: '审核' },
      { value: 'FileAddOutlined', label: '新建文档' },
      { value: 'FolderAddOutlined', label: '新建目录' },
    ],
  },
  {
    label: '标注与编辑',
    options: [
      { value: 'TagsOutlined', label: '标签' },
      { value: 'EditOutlined', label: '编辑' },
      { value: 'FormOutlined', label: '表单' },
      { value: 'HighlightOutlined', label: '高亮' },
      { value: 'FontColorsOutlined', label: '文本样式' },
      { value: 'CheckSquareOutlined', label: '勾选' },
      { value: 'CopyOutlined', label: '复制' },
      { value: 'DiffOutlined', label: '对比' },
    ],
  },
  {
    label: '医疗与人员',
    options: [
      { value: 'MedicineBoxOutlined', label: '医药箱' },
      { value: 'HeartOutlined', label: '心脏' },
      { value: 'FileProtectOutlined', label: '病历' },
      { value: 'ScheduleOutlined', label: '排班' },
      { value: 'MonitorOutlined', label: '监护' },
      { value: 'UserOutlined', label: '用户' },
      { value: 'TeamOutlined', label: '团队' },
      { value: 'SafetyOutlined', label: '安全防护' },
      { value: 'PlusSquareOutlined', label: '加号' },
    ],
  },
  {
    label: '接口与集成',
    options: [
      { value: 'ApiOutlined', label: '接口' },
      { value: 'LinkOutlined', label: '链接' },
      { value: 'NodeIndexOutlined', label: '节点' },
      { value: 'BranchesOutlined', label: '分支' },
      { value: 'MergeCellsOutlined', label: '合并' },
      { value: 'ShareAltOutlined', label: '分享' },
      { value: 'ClusterOutlined', label: '集群' },
      { value: 'ApartmentOutlined', label: '机构' },
      { value: 'SubnodeOutlined', label: '子节点' },
      { value: 'GatewayOutlined', label: '网关' },
      { value: 'RetweetOutlined', label: '流转' },
      { value: 'SwapOutlined', label: '交换' },
    ],
  },
  {
    label: '系统与运维',
    options: [
      { value: 'SettingOutlined', label: '设置' },
      { value: 'ToolOutlined', label: '工具' },
      { value: 'CloudOutlined', label: '云服务' },
      { value: 'KeyOutlined', label: '密钥' },
      { value: 'LockOutlined', label: '锁定' },
      { value: 'SafetyCertificateOutlined', label: '证书' },
      { value: 'AlertOutlined', label: '告警' },
      { value: 'BellOutlined', label: '通知' },
      { value: 'EyeOutlined', label: '监控' },
      { value: 'SyncOutlined', label: '同步' },
      { value: 'HistoryOutlined', label: '历史' },
      { value: 'RocketOutlined', label: '发布' },
      { value: 'SendOutlined', label: '发送' },
      { value: 'SearchOutlined', label: '搜索' },
      { value: 'FilterOutlined', label: '筛选' },
      { value: 'ScanOutlined', label: '扫描' },
      { value: 'QrcodeOutlined', label: '二维码' },
      { value: 'BarcodeOutlined', label: '条码' },
      { value: 'PrinterOutlined', label: '打印' },
      { value: 'SaveOutlined', label: '保存' },
      { value: 'UploadOutlined', label: '上传' },
      { value: 'DownloadOutlined', label: '下载' },
      { value: 'ImportOutlined', label: '导入' },
      { value: 'ExportOutlined', label: '导出' },
      { value: 'ReloadOutlined', label: '刷新' },
      { value: 'RedoOutlined', label: '重做' },
    ],
  },
  {
    label: '资产与机构',
    options: [
      { value: 'GoldOutlined', label: '资产' },
      { value: 'InboxOutlined', label: '归档' },
      { value: 'BankOutlined', label: '机构' },
      { value: 'ShopOutlined', label: '站点' },
      { value: 'CreditCardOutlined', label: '卡片' },
      { value: 'WalletOutlined', label: '钱包' },
    ],
  },
  {
    label: '时间与消息',
    options: [
      { value: 'ClockCircleOutlined', label: '时钟' },
      { value: 'CalendarOutlined', label: '日历' },
      { value: 'FieldTimeOutlined', label: '计时' },
      { value: 'HourglassOutlined', label: '沙漏' },
      { value: 'MessageOutlined', label: '消息' },
      { value: 'CommentOutlined', label: '评论' },
      { value: 'NotificationOutlined', label: '广播' },
      { value: 'MailOutlined', label: '邮件' },
      { value: 'PhoneOutlined', label: '电话' },
      { value: 'CustomerServiceOutlined', label: '客服' },
    ],
  },
  {
    label: '媒体与设备',
    options: [
      { value: 'VideoCameraOutlined', label: '视频' },
      { value: 'AudioOutlined', label: '音频' },
      { value: 'PictureOutlined', label: '图片' },
      { value: 'CameraOutlined', label: '相机' },
      { value: 'MobileOutlined', label: '手机' },
      { value: 'TabletOutlined', label: '平板' },
      { value: 'LaptopOutlined', label: '笔记本' },
      { value: 'DesktopOutlined', label: '桌面' },
      { value: 'WifiOutlined', label: '网络' },
      { value: 'SoundOutlined', label: '声音' },
      { value: 'PaperClipOutlined', label: '附件' },
      { value: 'PushpinOutlined', label: '图钉' },
      { value: 'SkinOutlined', label: '外观' },
    ],
  },
  {
    label: '状态与标记',
    options: [
      { value: 'StarOutlined', label: '星标' },
      { value: 'FlagOutlined', label: '旗帜' },
      { value: 'TrophyOutlined', label: '奖杯' },
      { value: 'FireOutlined', label: '热门' },
      { value: 'CrownOutlined', label: '皇冠' },
      { value: 'CheckCircleOutlined', label: '成功' },
      { value: 'CloseCircleOutlined', label: '失败' },
      { value: 'InfoCircleOutlined', label: '信息' },
      { value: 'QuestionCircleOutlined', label: '帮助' },
      { value: 'WarningOutlined', label: '警告' },
      { value: 'StopOutlined', label: '停止' },
      { value: 'PlayCircleOutlined', label: '播放' },
      { value: 'PauseCircleOutlined', label: '暂停' },
      { value: 'PlusCircleOutlined', label: '新增' },
      { value: 'MinusCircleOutlined', label: '减少' },
    ],
  },
  {
    label: '经典图标',
    options: [
      { value: 'Sparkles', label: '智能' },
      { value: 'BrainCircuit', label: '智能大脑' },
      { value: 'Bot', label: '机器人' },
      { value: 'Stethoscope', label: '听诊器' },
      { value: 'BookOpenText', label: '文档阅读' },
      { value: 'Home', label: '首页（旧）' },
      { value: 'Boxes', label: '应用集' },
      { value: 'Cpu', label: '芯片' },
      { value: 'FileText', label: '文档（旧）' },
      { value: 'FileSearch', label: '文件检索' },
      { value: 'Gauge', label: '仪表盘（旧）' },
      { value: 'GitFork', label: '分叉' },
      { value: 'GitBranch', label: '分支（旧）' },
      { value: 'Settings2', label: '设置（旧）' },
      { value: 'Menu', label: '菜单（旧）' },
      { value: 'Library', label: '库' },
      { value: 'PenLine', label: '编辑（旧）' },
      { value: 'LineChart', label: '折线图（旧）' },
      { value: 'Database', label: '数据库（旧）' },
      { value: 'Waypoints', label: '路径点' },
      { value: 'KeyRound', label: '密钥（旧）' },
      { value: 'Layers', label: '分层' },
      { value: 'LayoutDashboard', label: '看板' },
      { value: 'MessageSquare', label: '消息（旧）' },
      { value: 'MessageSquareText', label: '消息文本' },
      { value: 'Network', label: '网络（旧）' },
      { value: 'Tags', label: '标签（旧）' },
      { value: 'Workflow', label: '工作流' },
      { value: 'ClipboardList', label: '清单' },
      { value: 'ScanLine', label: '扫描（旧）' },
      { value: 'Activity', label: '活动' },
      { value: 'FileClock', label: '定时文档' },
      { value: 'Plug', label: '插件' },
    ],
  },
];

export const ICON_OPTIONS: IconOption[] = ICON_OPTION_GROUPS.flatMap((group) => group.options);
