const { test, expect } = require('@playwright/test');
const { installWorkflowFixture } = require('./workflowFixture.cjs');
test.use({ browserName: 'chromium', channel: process.env.WORKFLOW_BROWSER_CHANNEL || 'chrome', viewport: { width: 1680, height: 1040 } });
const base = process.env.WORKFLOW_TEST_URL || 'http://127.0.0.1:8000';
const url = `${base}/agent-hub/workflows?project=project-1`;
const choose = async (page, label, text) => {
  await page.getByLabel(label, { exact: true }).click();
  await page.locator('.ant-select-dropdown:visible,.mp-ant-select-dropdown:visible').getByText(text, { exact: true }).click();
};
test('model and rules are required before saving or generating, without grants', async ({ page }) => {
  const fixture = await installWorkflowFixture(page); const draft = fixture.deployments.get('project-1').draft;
  draft.defaultModelRevisionId = ''; draft.tasks[0].modelRevisionId = 'model-1'; draft.role.body = '  ';
  await page.goto(url);
  await expect(page.getByRole('tab', { name: '智能体配置', exact: true })).toHaveAttribute('aria-selected', 'true');
  await page.getByLabel('编排角色规则', { exact: true }).fill('   ');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await expect(page.getByText('请选择默认模型', { exact: true })).toBeVisible();
  await expect(page.getByText('请填写规则提示词', { exact: true })).toBeVisible();
  expect(fixture.mutations).toEqual([]);
  await choose(page, '编排默认模型', '通用对话模型 · local-test-model · a1234567');
  await page.getByRole('button', { name: '生成智能体', exact: true }).click();
  await expect(page.getByText('请填写规则提示词', { exact: true })).toBeVisible();
  expect(fixture.mutations).toEqual([]);
  await page.getByLabel('编排角色规则', { exact: true }).fill('必须依据事实回答。');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await expect.poll(() => fixture.mutations.filter(item => item.path.endsWith('/draft')).length).toBe(1);
  expect(fixture.deployments.get('project-1').draft.defaultModelRevisionId).toBe('model-1');
  expect(fixture.mutations.some(item => /grants/.test(item.path))).toBe(false);
});
test('template selection is required and saves its fixed revision', async ({ page }) => {
  const fixture = await installWorkflowFixture(page); await page.goto(url);
  await page.getByRole('button', { name: '智能体配置', exact: true }).click();
  await choose(page, '编排角色来源', '关联提示词模板');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await expect(page.getByText('请选择有效的规则提示词模板', { exact: true })).toBeVisible();
  expect(fixture.mutations).toEqual([]);
  await choose(page, '编排提示词模板', '企业助手模板 · 修订 · p1234567');
  await page.getByRole('button', { name: '保存草稿', exact: true }).click();
  await expect.poll(() => fixture.mutations.length).toBe(1);
  expect(fixture.deployments.get('project-1').draft.role).toEqual({ kind: 'template', revisionId: 'prompt-1' });
});
test('governance no longer has resource authorization or runtime prompt editors', async ({ page }) => {
  const fixture = await installWorkflowFixture(page);
  fixture.projects.push({ id: 'plat-fishbone', name: '鱼骨图分析', agentMode: 'external' });
  await page.goto(`${base}/agent-hub/settings?project=plat-fishbone`);
  await expect(page.getByRole('heading', { name: '治理设置', exact: true })).toBeVisible();
  await expect(page.getByRole('switch')).toHaveCount(0);
  await expect(page.getByRole('button', { name: /下一步.*绑定智能体|编辑.*提示词/ })).toHaveCount(0);
  await page.goto(`${base}/agent-hub/agents?project=plat-fishbone`);
  await expect(page.getByRole('heading', { name: '外部智能体配置', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '编辑鱼骨图分析提示词', exact: true }).click();
  await expect(page.getByRole('dialog', { name: '鱼骨图分析 · 智能体提示词' })).toBeVisible();
  await expect(page.getByLabel('SOUL 内容', { exact: true })).toHaveValue('共享角色规则');
  expect(fixture.mutations).toEqual([]);
});
test('an independent agent can select its configuration without any project', async ({ page }) => {
  const fixture = await installWorkflowFixture(page); fixture.projects.length = 0; fixture.deployments.clear();
  const agent = fixture.createAgent('无项目智能体', '主任务'); agent.draft.defaultModelRevisionId = '';
  await page.goto(`${base}/agent-hub/workflows?agent=${agent.summary.id}&mode=create`);
  await choose(page, '编排默认模型', '通用对话模型 · local-test-model · a1234567');
  await page.getByLabel('编排角色规则', { exact: true }).fill('独立智能体的规则。');
  await page.getByRole('button', { name: '生成智能体', exact: true }).click();
  await expect(page.getByText('编排检查通过', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '生成并保存', exact: true }).click();
  await expect.poll(() => agent.expectedRevision).toBe(2);
  expect(agent.draft.defaultModelRevisionId).toBe('model-1');
  expect(fixture.mutations.some(item => /grants/.test(item.path))).toBe(false);
});
test('direct version publication also refuses an incomplete agent', async ({ page }) => {
  const fixture = await installWorkflowFixture(page); const agent = fixture.createAgent('发布必填校验', '主任务');
  agent.draft.defaultModelRevisionId = ''; agent.draft.tasks[0].modelRevisionId = 'model-1';
  await page.goto(`${base}/agent-hub/agents?agent=${agent.summary.id}`);
  await page.locator('.hub-agent-detail').getByRole('button', { name: '发布版本', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '发布智能体版本 · 发布必填校验' });
  await dialog.getByLabel('发布说明', { exact: true }).fill('验证必填项');
  await dialog.getByRole('button', { name: '确认发布', exact: true }).click();
  await expect(dialog.getByText(/请选择默认模型/)).toBeVisible();
  expect(fixture.mutations.filter(item => item.path.endsWith('/versions'))).toHaveLength(0);
});
